### ISSUE TITLE
Crash when login with keycard

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1609]
# Problem

```
09-17 00:57:57.467 30220     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
09-17 00:57:57.467 30220     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x720fe86328]
09-17 00:57:57.467 30220     0 E Go      : 
09-17 00:57:57.467 30220     0 E Go      : goroutine 239 [running]:
09-17 00:57:57.468 30220     0 E Go      : github.com/status-im/status-go/vendor/github.com/status-im/status-protocol-go.(*Messenger).Installations(0x0, 0x4000415080, 0x0, 0x720f6fabb4, 0x4000088a80, 0x72130a8d80)
09-17 00:57:57.468 30220     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/status-im/status-protocol-go/messenger.go:421 +0x18
09-17 00:57:57.468 30220     0 E Go      : github.com/status-im/status-go/services/shhext.(*PublicAPI).GetOurInstallations(0x40003786e0, 0x0, 0x0, 0x0, 0x0, 0x0)
09-17 00:57:57.468 30220     0 E Go      : 	/build/go/src/github.com/status-im/status-go/services/shhext/api.go:611 +0x28
09-17 00:57:57.468 30220     0 E Go      : reflect.Value.call(0x4000274c60, 0x400038aac8, 0x13, 0x72101d9732, 0x4, 0x40011dce68, 0x1, 0x1, 0x4141414141414141, 0x5141414141414141, ...)
09-17 00:57:57.468 30220     0 E Go      : 	/nix/store/wyb0s95nmispvzaawdva79k6nyn8pxm2-go-1.11.5/share/go/src/reflect/value.go:447 +0x340
09-17 00:57:57.468 30220     0 E Go      : reflect.Value.Call(0x4000274c60, 0x400038aac8, 0x13, 0x4000459668, 0x1, 0x1, 0x4141414141414141, 0x4141414141414141, 0x4141414141414141)
09-17 00:57:57.468 30220     0 E Go      : 	/nix/store/wyb0s95nmispvzaawdva79k6nyn8pxm2-go-1.11.5/share/go/src/reflect/value.go:308 +0x7c
09-17 00:57:57.468 30220     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*Server).handle(0x40003cb260, 0x7210b74ea0, 0x40011a2840, 0x7210b7a760, 0x4000208140, 0x4000527c20, 0x4141414141414141, 0x720faf2974, 0x4141414100000008)
09-17 00:57:57.468 30220     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/server.go:309 +0x554
09-17 00:57:57.468 30220     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*Server).exec(0x40003cb260, 0x7210b74ea0, 0x40011a2840, 0x7210b7a760, 0x4000208140, 0x4000527c20)
09-17 00:57:57.468 30220     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/server.go:330 +0x148
09-17 00:57:57.468 30220     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0x40002ba000, 0x40003cb260, 0x400033c000, 0x7210b7a760, 0x4000208140, 0x400041c708, 0x1, 0x1, 0x4141414141414100)
09-17 00:57:57.468 30220     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/server.go:204 +0x8c
09-17 00:57:57.468 30220     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
09-17 00:57:57.468 30220     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/server.go:199 +0x1f8
09-17 00:57:57.468 30220 30394 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 30394 (mqt_native_modu), pid 30220 (tus.ethereum.pr)
```

**Comment by yenda** [comment]
@gravityblast sorry after looking at earlier log this was caused by leftover data
