### ISSUE TITLE
Consistently flaky Jenkins unit tests

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#1978]
# Problem
Jenkins unit tests will consistently fail ~~even if all the tests pass~~ (there was a failing test, I just didn't notice them in the full test log). The tests can be passed mostly by retesting and making no changes to the code.

* [Recent tests](https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/activity)
* [Specific test that failed at the very end of unit test](https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-1969/12/pipeline)
* [Full log](https://ci.status.im/blue/rest/organizations/jenkins/pipelines/status-go/pipelines/prs/pipelines/tests/branches/PR-1969/runs/12/nodes/73/steps/76/log/?start=0)
<details>
<summary>Sample log data</summary>

```text
[2020-05-14T14:46:52.615Z] + make test-unit
[2020-05-14T14:46:52.880Z] go test -v -failfast github.com/status-im/status-go/account github.com/status-im/status-go/account/generator github.com/status-im/status-go/api github.com/status-im/status-go/appdatabase github.com/status-im/status-go/appdatabase/migrations github.com/status-im/status-go/appdatabase/migrations/sql github.com/status-im/status-go/bridge github.com/status-im/status-go/cmd/bootnode github.com/status-im/status-go/cmd/node-canary github.com/status-im/status-go/cmd/statusd github.com/status-im/status-go/cmd/statusd/topics github.com/status-im/status-go/contracts github.com/status-im/status-go/contracts/ens github.com/status-im/status-go/contracts/ens/contract github.com/status-im/status-go/db github.com/status-im/status-go/discovery github.com/status-im/status-go/eth-node/bridge/geth github.com/status-im/status-go/eth-node/bridge/geth/ens github.com/status-im/status-go/eth-node/core/types github.com/status-im/status-go/eth-node/crypto github.com/status-im/status-go/eth-node/crypto/ecies github.com/status-im/status-go/eth-node/keystore github.com/status-im/status-go/eth-node/types github.com/status-im/status-go/eth-node/types/ens github.com/status-im/status-go/exportlogs github.com/status-im/status-go/logutils github.com/status-im/status-go/mailserver github.com/status-im/status-go/mailserver/migrations github.com/status-im/status-go/mailserver/registry github.com/status-im/status-go/metrics github.com/status-im/status-go/metrics/node github.com/status-im/status-go/mobile github.com/status-im/status-go/multiaccounts github.com/status-im/status-go/multiaccounts/accounts github.com/status-im/status-go/multiaccounts/migrations github.com/status-im/status-go/multiaccounts/migrations/sql github.com/status-im/status-go/node github.com/status-im/status-go/notifier github.com/status-im/status-go/params github.com/status-im/status-go/peers github.com/status-im/status-go/peers/verifier github.com/status-im/status-go/profiling github.com/status-im/status-go/protocol github.com/status-im/status-go/protocol/applicationmetadata github.com/status-im/status-go/protocol/datasync github.com/status-im/status-go/protocol/datasync/peer github.com/status-im/status-go/protocol/encryption github.com/status-im/status-go/protocol/encryption/migrations github.com/status-im/status-go/protocol/encryption/migrations/sqlite github.com/status-im/status-go/protocol/encryption/multidevice github.com/status-im/status-go/protocol/encryption/publisher github.com/status-im/status-go/protocol/encryption/sharedsecret github.com/status-im/status-go/protocol/identity/alias github.com/status-im/status-go/protocol/identity/identicon github.com/status-im/status-go/protocol/images github.com/status-im/status-go/protocol/internal/sqlite github.com/status-im/status-go/protocol/migrations github.com/status-im/status-go/protocol/migrations/sqlite github.com/status-im/status-go/protocol/protobuf github.com/status-im/status-go/protocol/sqlite github.com/status-im/status-go/protocol/subscription github.com/status-im/status-go/protocol/transport github.com/status-im/status-go/protocol/transport/waku github.com/status-im/status-go/protocol/transport/waku/migrations github.com/status-im/status-go/protocol/transport/waku/migrations/sqlite github.com/status-im/status-go/protocol/transport/whisper github.com/status-im/status-go/protocol/transport/whisper/migrations github.com/status-im/status-go/protocol/transport/whisper/migrations/sqlite github.com/status-im/status-go/protocol/tt github.com/status-im/status-go/protocol/v1 github.com/status-im/status-go/protocol/zaputil github.com/status-im/status-go/rpc github.com/status-im/status-go/rtt github.com/status-im/status-go/services github.com/status-im/status-go/services/accounts github.com/status-im/status-go/services/browsers github.com/status-im/status-go/services/ext github.com/status-im/status-go/services/ext/mailservers github.com/status-im/status-go/services/mailservers github.com/status-im/status-go/services/nodebridge github.com/status-im/status-go/services/peer github.com/status-im/status-go/services/permissions github.com/status-im/status-go/services/personal github.com/status-im/status-go/services/rpcfilters github.com/status-im/status-go/services/shhext github.com/status-im/status-go/services/status github.com/status-im/status-go/services/subscriptions github.com/status-im/status-go/services/typeddata github.com/status-im/status-go/services/typeddata/eip712example github.com/status-im/status-go/services/wakuext github.com/status-im/status-go/services/wallet github.com/status-im/status-go/services/wallet/erc20 github.com/status-im/status-go/services/wallet/ierc20 github.com/status-im/status-go/signal github.com/status-im/status-go/sqlite github.com/status-im/status-go/static github.com/status-im/status-go/static/mailserver_db_migrations github.com/status-im/status-go/t github.com/status-im/status-go/t/devtests github.com/status-im/status-go/t/devtests/eventer github.com/status-im/status-go/t/devtests/miner github.com/status-im/status-go/t/devtests/testchain github.com/status-im/status-go/t/helpers github.com/status-im/status-go/t/utils github.com/status-im/status-go/timesource github.com/status-im/status-go/transactions github.com/status-im/status-go/waku github.com/status-im/status-go/waku/common github.com/status-im/status-go/waku/v0 github.com/status-im/status-go/waku/v1
[2020-05-14T14:46:53.821Z] # gopkg.in/olebedev/go-duktape.v3
[2020-05-14T14:46:53.821Z] In file included from _cgo_export.c:4:0:
[2020-05-14T14:46:53.821Z] debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
[2020-05-14T14:47:04.601Z] === RUN TestVerifyAccountPassword
[2020-05-14T14:47:04.601Z] --- PASS: TestVerifyAccountPassword (0.10s)
[2020-05-14T14:47:04.601Z] === RUN TestVerifyAccountPasswordWithAccountBeforeEIP55
[2020-05-14T14:47:04.601Z] --- PASS: TestVerifyAccountPasswordWithAccountBeforeEIP55 (0.03s)
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestAccounts
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestAddressToDecryptedAccountSuccess
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestAddressToDecryptedAccountWrongAddress
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestAddressToDecryptedAccountWrongPassword
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestLogout
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestOnboarding
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestRecoverAccount
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestSelectAccountSuccess
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestSelectAccountWrongAddress
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestSelectAccountWrongPassword
[2020-05-14T14:47:04.601Z] === RUN TestManagerTestSuite/TestSetChatAccount
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite (7.92s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestAccounts (0.80s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestAddressToDecryptedAccountSuccess (0.70s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestAddressToDecryptedAccountWrongAddress (0.54s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestAddressToDecryptedAccountWrongPassword (0.60s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestLogout (0.52s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestOnboarding (1.46s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestRecoverAccount (0.71s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestSelectAccountSuccess (0.87s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestSelectAccountWrongAddress (0.51s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestSelectAccountWrongPassword (0.67s)
[2020-05-14T14:47:04.601Z] --- PASS: TestManagerTestSuite/TestSetChatAccount (0.54s)

...

[2020-05-14T14:49:59.143Z] === RUN TestEncodeDecodeVersionedResponse
[2020-05-14T14:49:59.143Z] --- PASS: TestEncodeDecodeVersionedResponse (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestTopicOrBloomMatch
[2020-05-14T14:49:59.143Z] --- PASS: TestTopicOrBloomMatch (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestTopicOrBloomMatchFullNode
[2020-05-14T14:49:59.143Z] --- PASS: TestTopicOrBloomMatchFullNode (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestPeerBasic
[2020-05-14T14:49:59.143Z] --- PASS: TestPeerBasic (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestSendBundle
[2020-05-14T14:49:59.143Z] --- PASS: TestSendBundle (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestEncodeDecodeRLP
[2020-05-14T14:49:59.143Z] --- PASS: TestEncodeDecodeRLP (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestBackwardCompatibility
[2020-05-14T14:49:59.143Z] --- PASS: TestBackwardCompatibility (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestForwardCompatibility
[2020-05-14T14:49:59.143Z] --- PASS: TestForwardCompatibility (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestInitRLPKeyFields
[2020-05-14T14:49:59.143Z] --- PASS: TestInitRLPKeyFields (0.00s)
[2020-05-14T14:49:59.143Z] PASS
[2020-05-14T14:49:59.143Z] ok github.com/status-im/status-go/waku/v0 0.032s
[2020-05-14T14:49:59.143Z] === RUN TestEncodeDecodeVersionedResponse
[2020-05-14T14:49:59.143Z] --- PASS: TestEncodeDecodeVersionedResponse (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestTopicOrBloomMatch
[2020-05-14T14:49:59.143Z] --- PASS: TestTopicOrBloomMatch (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestTopicOrBloomMatchFullNode
[2020-05-14T14:49:59.143Z] --- PASS: TestTopicOrBloomMatchFullNode (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestPeerBasic
[2020-05-14T14:49:59.143Z] --- PASS: TestPeerBasic (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestSendBundle
[2020-05-14T14:49:59.143Z] --- PASS: TestSendBundle (0.00s)
[2020-05-14T14:49:59.143Z] === RUN TestEncodeDecodeRLP
[2020-05-14T14:49:59.144Z] --- PASS: TestEncodeDecodeRLP (0.00s)
[2020-05-14T14:49:59.144Z] === RUN TestBackwardCompatibility
[2020-05-14T14:49:59.144Z] --- PASS: TestBackwardCompatibility (0.00s)
[2020-05-14T14:49:59.144Z] === RUN TestForwardCompatibility
[2020-05-14T14:49:59.144Z] --- PASS: TestForwardCompatibility (0.00s)
[2020-05-14T14:49:59.144Z] === RUN TestInitRLPKeyFields
[2020-05-14T14:49:59.144Z] --- PASS: TestInitRLPKeyFields (0.00s)
[2020-05-14T14:49:59.144Z] PASS
[2020-05-14T14:49:59.144Z] ok github.com/status-im/status-go/waku/v1 0.031s
[2020-05-14T14:49:59.144Z] FAIL
[2020-05-14T14:49:59.144Z] Makefile:263: recipe for target 'test-unit' failed
[2020-05-14T14:49:59.144Z] make: *** [test-unit] Error 2
script returned exit code 2
```

</details>

# Implementation

* [x] Find the cause of these fails
  * At least one cause has been found, see https://github.com/status-im/status-go/issues/1978#issuecomment-652389480
* [ ] Implement a fix for these fails

# Future Steps
be aware if this type of consistent failing is reintroduced.

**Comment by Samyoul** [comment]
Analysis from @andremedeiro shows that fail is here 

https://github.com/status-im/status-go/blob/develop/peers/peerpool_test.go#L513

Error log

```text
[2020-06-18T07:40:31.467Z] === RUN   TestPeerPoolSimulationSuite
[2020-06-18T07:40:31.467Z] === RUN   TestPeerPoolSimulationSuite/TestMailServerPeersDiscovery
[2020-06-18T07:40:31.467Z] --- FAIL: TestPeerPoolSimulationSuite (1.07s)
[2020-06-18T07:40:31.467Z]     --- FAIL: TestPeerPoolSimulationSuite/TestMailServerPeersDiscovery (1.06s)
[2020-06-18T07:40:31.467Z]         suite.go:63: test panicked: runtime error: index out of range [0] with length 0
[2020-06-18T07:40:31.467Z]             goroutine 146 [running]:
[2020-06-18T07:40:31.467Z]             runtime/debug.Stack(0xc004b715d8, 0x10078c0, 0xc00369ad20)
[2020-06-18T07:40:31.467Z]             	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
[2020-06-18T07:40:31.467Z]             github.com/stretchr/testify/suite.failOnPanic(0xc00026e200)
[2020-06-18T07:40:31.467Z]             	/home/jenkins/workspace/status-go_prs_tests_PR-1992/pkg/mod/github.com/stretchr/testify@v1.5.1/suite/suite.go:63 +0x57
[2020-06-18T07:40:31.467Z]             panic(0x10078c0, 0xc00369ad20)
[2020-06-18T07:40:31.467Z]             	/usr/local/go/src/runtime/panic.go:679 +0x1b2
[2020-06-18T07:40:31.467Z]             github.com/status-im/status-go/peers.(*PeerPoolSimulationSuite).TestMailServerPeersDiscovery(0xc000383500)
[2020-06-18T07:40:31.467Z]             	/home/jenkins/workspace/status-go_prs_tests_PR-1992/src/github.com/status-im/status-go/peers/peerpool_test.go:513 +0x1459
[2020-06-18T07:40:31.467Z]             reflect.Value.call(0xc0000bfb00, 0xc000010fe0, 0x13, 0x10a267f, 0x4, 0xc0000f3ef8, 0x1, 0x1, 0xc0000f3d08, 0x41afda, ...)
[2020-06-18T07:40:31.467Z]             	/usr/local/go/src/reflect/value.go:460 +0x5f6
[2020-06-18T07:40:31.467Z]             reflect.Value.Call(0xc0000bfb00, 0xc000010fe0, 0x13, 0xc0000f3ef8, 0x1, 0x1, 0x349, 0x349014f7b08, 0xfa)
[2020-06-18T07:40:31.467Z]             	/usr/local/go/src/reflect/value.go:321 +0xb4
[2020-06-18T07:40:31.467Z]             github.com/stretchr/testify/suite.Run.func2(0xc00026e200)
[2020-06-18T07:40:31.467Z]             	/home/jenkins/workspace/status-go_prs_tests_PR-1992/pkg/mod/github.com/stretchr/testify@v1.5.1/suite/suite.go:137 +0x36b
[2020-06-18T07:40:31.467Z]             testing.tRunner(0xc00026e200, 0xc000100680)
[2020-06-18T07:40:31.467Z]             	/usr/local/go/src/testing/testing.go:909 +0xc9
[2020-06-18T07:40:31.467Z]             created by testing.(*T).Run
[2020-06-18T07:40:31.467Z]             	/usr/local/go/src/testing/testing.go:960 +0x350
[2020-06-18T07:40:31.467Z] FAIL
[2020-06-18T07:40:31.467Z] FAIL	github.com/status-im/status-go/peers	1.157s
```

**Comment by cammellos** [comment]
This test should not be flaky anymore.
Some of the tests that are still flaky:

- PushNotifications tests in messenger. This are valuable imo and should be kept, I will look at those.
- Bridge tests. These tests often hangs, and it means we have to wait for the timeout for them to stop. I would probably remove them as we'll eventually remove the bridge, so not worth fixing, what do you think?
- TestECR20 : this test crashes estimate gas sometimes, not sure exactly what it does, but that part of the codebase is rarely touched, so it would be a candidate for removal.

**Comment by Ferossgp** [comment]
One more test:

https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-2026/42/pipeline#step-76-log-930

```
[2020-10-07T13:34:40.186Z] --- FAIL: TestShhExtSuite (1.36s)

[2020-10-07T13:34:40.186Z]     --- PASS: TestShhExtSuite/TestFailedRequestWithUnknownMailServerPeer (0.49s)

[2020-10-07T13:34:40.186Z]     --- FAIL: TestShhExtSuite/TestMultipleRequestMessagesWithoutForce (0.87s)

[2020-10-07T13:34:40.186Z]         api_geth_test.go:344: 

[2020-10-07T13:34:40.186Z]             	Error Trace:	api_geth_test.go:344

[2020-10-07T13:34:40.186Z]             	Error:      	Received unexpected error:

[2020-10-07T13:34:40.186Z]             	            	Could not find peer with ID: c498cd582b950c6b265cb4ba58f84309333577bea2c8183138ab7840685aa805

[2020-10-07T13:34:40.186Z]             	Test:       	TestShhExtSuite/TestMultipleRequestMessagesWithoutForce

[2020-10-07T13:34:40.186Z] FAIL

[2020-10-07T13:34:40.186Z] FAIL	github.com/status-im/status-go/services/shhext	2.197s

```

**Comment by cammellos** [comment]
Another flaky test I have noticed is:
```
[2020-10-08T13:30:30.125Z] goroutine 25870 [syscall, 29 minutes]:
[2020-10-08T13:30:30.125Z] github.com/mutecomm/go-sqlcipher._Cfunc_sqlite3_prepare_v2(0x7f453802cfb8, 0x7f4538003540, 0xc0ffffffff, 0xc000010428, 0xc000010430, 0x0)
[2020-10-08T13:30:30.125Z] 	_cgo_gotypes.go:563 +0x4d
[2020-10-08T13:30:30.125Z] github.com/mutecomm/go-sqlcipher.(*SQLiteConn).prepare.func2(0xc0002e35e0, 0x7f4538003540, 0xc000010428, 0xc000010430, 0x466720)
[2020-10-08T13:30:30.125Z] 	/home/jenkins/workspace/status-go_prs_tests_PR-2056/pkg/mod/github.com/mutecomm/go-sqlcipher@v0.0.0-20190227152316-55dbde17881f/sqlite3.go:505 +0x168
[2020-10-08T13:30:30.125Z] github.com/mutecomm/go-sqlcipher.(*SQLiteConn).prepare(0xc0002e35e0, 0x1435cc0, 0xc0000b4010, 0xc00052c360, 0x17, 0x0, 0x0, 0x0, 0x0)
[2020-10-08T13:30:30.125Z] 	/home/jenkins/workspace/status-go_prs_tests_PR-2056/pkg/mod/github.com/mutecomm/go-sqlcipher@v0.0.0-20190227152316-55dbde17881f/sqlite3.go:505 +0x102
[2020-10-08T13:30:30.125Z] github.com/mutecomm/go-sqlcipher.(*SQLiteConn).exec(0xc0002e35e0, 0x1435cc0, 0xc0000b4010, 0xc00052c360, 0x17, 0x1d0b020, 0x0, 0x0, 0x1d0b020, 0xc0006249f0, ...)
[2020-10-08T13:30:30.125Z] 	/home/jenkins/workspace/status-go_prs_tests_PR-2056/pkg/mod/github.com/mutecomm/go-sqlcipher@v0.0.0-20190227152316-55dbde17881f/sqlite3.go:220 +0xd2
[2020-10-08T13:30:30.125Z] github.com/mutecomm/go-sqlcipher.(*SQLiteConn).Exec(0xc0002e35e0, 0xc00052c360, 0x17, 0x1d0b020, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1)
[2020-10-08T13:30:30.125Z] 	/home/jenkins/workspace/status-go_prs_tests_PR-2056/pkg/mod/github.com/mutecomm/go-sqlcipher@v0.0.0-20190227152316-55dbde17881f/sqlite3.go:214 +0x131
[2020-10-08T13:30:30.125Z] database/sql.ctxDriverExec(0x1435cc0, 0xc0000b4010, 0x0, 0x0, 0x7f457c08c750, 0xc0002e35e0, 0xc00052c360, 0x17, 0x1d0b020, 0x0, ...)
[2020-10-08T13:30:30.125Z] 	/usr/local/go/src/database/sql/ctxutil.go:43 +0x157

```

Seems like sqlcipher hangs sometimes opening the database (that's something we never noticed on production, so might be related to tests only), but not exactly clear what it is.
Is seems it might deadlock if multiple threads are re-using the same connection, but that should not be the case, for now I will use a inmemory database for those tests, while other will still use a file.

**Comment by cammellos** [comment]
Another flaky test
https://ci.status.im/blue/rest/organizations/jenkins/pipelines/status-go/pipelines/prs/pipelines/tests/branches/PR-2060/runs/2/nodes/73/log/?start=0
```
 --- FAIL: TestERC20Transfers (17.65s)
[2020-10-21T07:59:57.674Z]     --- PASS: TestERC20Transfers/TestInRange (8.95s)
[2020-10-21T07:59:57.674Z]     --- PASS: TestERC20Transfers/TestInboundEvent (5.14s)
[2020-10-21T07:59:57.674Z]     --- FAIL: TestERC20Transfers/TestNoEvents (3.55s)
[2020-10-21T07:59:57.674Z]         downloader_test.go:204: 
[2020-10-21T07:59:57.674Z]             	Error Trace:	downloader_test.go:204
[2020-10-21T07:59:57.674Z]             	            				suite.go:123
[2020-10-21T07:59:57.674Z]             	Error:      	Received unexpected error:
[2020-10-21T07:59:57.674Z]             	            	failed to estimate gas needed: method handler crashed
[2020-10-21T07:59:57.674Z]             	Test:       	TestERC20Transfers/TestNoEvents
```

**Comment by cammellos** [comment]
and another one:
```
[2020-10-22T10:42:01.549Z] --- FAIL: TestMessengerPushNotificationSuite (11.51s)
[2020-10-22T10:42:01.549Z]     --- PASS: TestMessengerPushNotificationSuite/TestContactCode (0.69s)
[2020-10-22T10:42:01.549Z]     --- FAIL: TestMessengerPushNotificationSuite/TestReceivePushNotification (10.82s)
[2020-10-22T10:42:01.549Z]         push_notification_test.go:227: 
[2020-10-22T10:42:01.549Z]             	Error Trace:	push_notification_test.go:227
[2020-10-22T10:42:01.549Z]             	Error:      	Received unexpected error:
[2020-10-22T10:42:01.549Z]             	            	info not fetched
[2020-10-22T10:42:01.549Z]             	Test:       	TestMessengerPushNotificationSuite/TestReceivePushNotification
[2020-10-22T10:42:01.549Z] FAIL
```
[log.txt](https://github.com/status-im/status-go/files/5422168/log.txt)

**Comment by cammellos** [comment]
another one reported:

```
 --- FAIL: TestERC20Transfers (25.93s)
[2020-11-02T10:13:14.984Z]     --- PASS: TestERC20Transfers/TestInRange (9.45s)
[2020-11-02T10:13:14.984Z]     --- PASS: TestERC20Transfers/TestInboundEvent (5.85s)
[2020-11-02T10:13:14.984Z]     --- PASS: TestERC20Transfers/TestNoEvents (5.79s)
[2020-11-02T10:13:14.984Z]     --- FAIL: TestERC20Transfers/TestOutboundEvent (4.84s)
[2020-11-02T10:13:14.984Z]         downloader_test.go:204: 
[2020-11-02T10:13:14.984Z]                 Error Trace:    downloader_test.go:204
[2020-11-02T10:13:14.984Z]                                             suite.go:123
[2020-11-02T10:13:14.984Z]                 Error:          Received unexpected error:
[2020-11-02T10:13:14.984Z]                                 failed to estimate gas needed: method handler crashed
[2020-11-02T10:13:14.984Z]                 Test:           TestERC20Transfers/TestOutboundEvent
```

**Comment by cammellos** [comment]
Another instance
[log.txt](https://github.com/status-im/status-go/files/5480215/log.txt)

**Comment by cammellos** [comment]
And another:

```

[2020-11-03T19:02:52.017Z]     --- SKIP: TestPeerPoolSimulationSuite/TestSingleTopicDiscoveryWithFailoverRendezvous (0.00s)
[2020-11-03T19:02:52.017Z]         peerpool_test.go:180: Skipping due to being flaky
[2020-11-03T19:02:52.017Z]     --- FAIL: TestPeerPoolSimulationSuite/TestUpdateTopicLimits (0.01s)
[2020-11-03T19:02:52.017Z]         peerpool_test.go:91: 
[2020-11-03T19:02:52.017Z]             	Error Trace:	peerpool_test.go:91
[2020-11-03T19:02:52.017Z]             	            				peerpool_test.go:408
[2020-11-03T19:02:52.017Z]             	Error:      	Received unexpected error:
[2020-11-03T19:02:52.017Z]             	            	listen udp [::]:36995: bind: address already in use
[2020-11-03T19:02:52.017Z]             	Test:       	TestPeerPoolSimulationSuite/TestUpdateTopicLimits
```

**Comment by cammellos** [comment]
another one:

```
[2020-12-08T15:25:36.178Z] === RUN   TestPeerPoolSimulationSuite/TestPeerPoolCacheEthV5
[2020-12-08T15:25:36.178Z] panic: runtime error: invalid memory address or nil pointer dereference
[2020-12-08T15:25:36.178Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8642ea]
[2020-12-08T15:25:36.178Z] 
[2020-12-08T15:25:36.178Z] goroutine 364 [running]:
[2020-12-08T15:25:36.178Z] github.com/ethereum/go-ethereum/p2p/discv5.(*Network).SearchTopic(0x0, 0x10bf368, 0x8, 0xc004e00150, 0xc006fe2720, 0xc004e001c0)
[2020-12-08T15:25:36.178Z]     /home/jenkins/workspace/status-go_prs_tests_PR-2093/pkg/mod/github.com/status-im/go-ethereum@v1.9.5-status.9/p2p/discv5/net.go:303 +0x3a
[2020-12-08T15:25:36.178Z] github.com/status-im/status-go/discovery.(*DiscV5).Discover(0xc004deaa00, 0x10bf368, 0x8, 0xc004e00150, 0xc006fe2720, 0xc004e001c0, 0x0, 0x0)
[2020-12-08T15:25:36.178Z]     /home/jenkins/workspace/status-go_prs_tests_PR-2093/src/github.com/status-im/status-go/discovery/discv5.go:85 +0x61
[2020-12-08T15:25:36.178Z] github.com/status-im/status-go/peers.(*TopicPool).StartSearch.func1(0xc00674e200, 0xc006fe2720, 0xc004e001c0)
[2020-12-08T15:25:36.178Z]     /home/jenkins/workspace/status-go_prs_tests_PR-2093/src/github.com/status-im/status-go/peers/topicpool.go:444 +0x80
[2020-12-08T15:25:36.178Z] created by github.com/status-im/status-go/peers.(*TopicPool).StartSearch
[2020-12-08T15:25:36.178Z]     /home/jenkins/workspace/status-go_prs_tests_PR-2093/src/github.com/status-im/status-go/peers/topicpool.go:443 +0x35b
[2020-12-08T15:25:36.178Z] FAIL    github.com/status-im/status-go/peers    2.948s
[2020-12-08T15:25:36.178Z] === RUN   TestLocalVerifierForNodeIDTypes
[2020-12-08T15:25:36.178Z] --- PASS: TestLocalVerifierForNodeIDTypes (0.00s)

```

**Comment by cammellos** [comment]
One fix for push notification tests https://github.com/status-im/status-go/pull/2118
