### ISSUE TITLE
index out of range error when connecting with Android app

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#2328]
# Problem

Node `v0.83.19` crashes when Mobile peer attempts to connect.

# Logs

```
INFO [08-24|11:01:40.329] handling peer                            peerID=0xf17130ca7d69f60e31a9702d00bb24d9134dd864cd17f7a3bdeb5cf44ca80b8d
INFO [08-24|11:01:40.781] failed to decode p2p request message (deprecated) peerID=0xf17130ca7d69f60e31a9702d00bb24d9134dd864cd17f7a3bdeb5cf44ca80b8d error="invalid message: (code 7e) (size 142) rlp: input string too long for uint32, decoding into (common.Envelope)(common.rlpenv).Expiry"
INFO [08-24|11:01:40.781] [mailserver:DeliverMail] delivering mail peerID=0xf17130ca7d69f60e31a9702d00bb24d9134dd864cd17f7a3bdeb5cf44ca80b8d requestID=0x3931356239386139383763313435383461323363656165323233616233336632
INFO [08-24|11:01:40.781] [mailserver:DeliverMail] processing request peerID=0xf17130ca7d69f60e31a9702d00bb24d9134dd864cd17f7a3bdeb5cf44ca80b8d requestID=0x3931356239386139383763313435383461323363656165323233616233336632 lower=1,629,802,229 upper=1,629,802,900 bloom=[] topics="[[135 239 55 47] [114 166 24 64] [99 20 96 136] [127 71 66 198] [5 219 24 157] [247 3 47 5] [141 193 10 205] [62 72 245 243] [5 237 142 65] [205 66 55 96] [231 209 224 45] [136 61 91 231] [124 84 165 48] [175 38 234 83] [218 202 132 168] [56 226 88 32] [2 99 160 18] [179 214 159 245]]" limit=1000 cursor=[] batch=true
INFO [08-24|11:01:40.781] [mailserver:processRequestInBundles] processing request requestID=0x3931356239386139383763313435383461323363656165323233616233336632 limit=1000
panic: runtime error: index out of range [0] with length 0
goroutine 942 [running]:
github.com/status-im/status-go/eth-node/types.BloomFilterMatch(0x2c738f8, 0x0, 0x0, 0xc001dfcbc0, 0x40, 0x40, 0x9f2769)
	/go/src/github.com/status-im/status-go/eth-node/types/topic.go:69 +0x8d
github.com/status-im/status-go/mailserver.(*LevelDBIterator).GetEnvelope(0xc001cb9310, 0x2c738f8, 0x0, 0x0, 0xc001d6d7f8, 0x4, 0x4, 0x2, 0x177aba0)
	/go/src/github.com/status-im/status-go/mailserver/mailserver_db_leveldb.go:55 +0x181
github.com/status-im/status-go/mailserver.(*mailServer).processRequestInBundles(0xc000278600, 0x1ed3060, 0xc001cb9310, 0x2c738f8, 0x0, 0x0, 0xc00000c1e0, 0x12, 0x13, 0x3e8, ...)
	/go/src/github.com/status-im/status-go/mailserver/mailserver.go:759 +0x32e
github.com/status-im/status-go/mailserver.(*mailServer).DeliverMail(0xc000278600, 0xef6697dca3071f1, 0xd924bb002d70a931, 0xa3f717cd64d84d13, 0x8d0ba84cf45cebbd, 0x3961383962353139, 0x3438353431633738, 0x3265616563333261, 0x3266333362613332, 0x6124d1946124cef5, ...)
	/go/src/github.com/status-im/status-go/mailserver/mailserver.go:533 +0x1082
github.com/status-im/status-go/mailserver.(*WakuMailServer).Deliver(0xc000837350, 0xc001d62780, 0x20, 0x20, 0xc001d62760, 0x20, 0x20, 0x6124d1946124cef5, 0x3e8, 0x2c738f8, ...)
	/go/src/github.com/status-im/status-go/mailserver/mailserver.go:130 +0x2e8
github.com/status-im/status-go/waku.(*Waku).OnMessagesRequest(0xc000490800, 0xc001d62760, 0x20, 0x20, 0x6124d1946124cef5, 0x3e8, 0x2c738f8, 0x0, 0x0, 0x2c738f8, ...)
	/go/src/github.com/status-im/status-go/waku/waku.go:1190 +0x89
github.com/status-im/status-go/waku/v1.(*Peer).handleP2PRequestCode(0xc00184ee00, 0x7e, 0x8e, 0x1e9ec40, 0xc00108adb0, 0xc04152452e8d3f56, 0xbfebf5ee5, 0x2c49fe0, 0x0, 0x0, ...)
	/go/src/github.com/status-im/status-go/waku/v1/peer.go:362 +0xc1c
github.com/status-im/status-go/waku/v1.(*Peer).handlePacket(0xc00184ee00, 0x7e, 0x8e, 0x1e9ec40, 0xc00108ad80, 0xc04152452e8d3f56, 0xbfebf5ee5, 0x2c49fe0, 0x0, 0x0, ...)
	/go/src/github.com/status-im/status-go/waku/v1/peer.go:271 +0x1e88
github.com/status-im/status-go/waku/v1.(*Peer).Run(0xc00184ee00, 0x0, 0x0)
	/go/src/github.com/status-im/status-go/waku/v1/peer.go:236 +0x15a
github.com/status-im/status-go/waku.(*Waku).HandlePeer(0xc000490800, 0x1ef1f80, 0xc00184ee00, 0x1eb6de0, 0xc000822960, 0x0, 0x0)
	/go/src/github.com/status-im/status-go/waku/waku.go:1127 +0x564
github.com/status-im/status-go/waku.(*Waku).handlePeerV1(0xc000490800, 0xc00073dd40, 0x1eb6de0, 0xc000822960, 0x0, 0x0)
	/go/src/github.com/status-im/status-go/waku/waku.go:1094 +0xcc
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc00073dd40, 0xc000822960, 0x1eb6de0, 0xc000822960)
	/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:407 +0xa3
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:405 +0x203
```

**Comment by jakubgs** [comment]
I tested this using a PR build from https://github.com/status-im/status-react/pull/12479 which uses `v0.83.16`.

**Comment by jakubgs** [comment]
@rasom I doubt it's your PR that caused this. I tested a few PR builds, including https://github.com/status-im/status-react/pull/12475.

**Comment by jakubgs** [comment]
Interestingly enough this also happens on `v0.79.11`.

**Comment by cammellos** [comment]
It happens because we don't send a bloom filter anymore with ms queries, and the leveldb part is not handling topics yet
