### ISSUE TITLE
Node crashes when using Waku V2 and Disc V5

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#3231]
# Problem

It just explodes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x127edea]

goroutine 321 [running]:
github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).SetBootnodes(...)
	/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:186
github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).SetDiscV5Bootnodes(0x22cd7a7?, {0xc000010d00?, 0x1e7dd60?, 0xc0037ae600?})
	/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:744 +0x6a
github.com/status-im/status-go/wakuv2.(*Waku).restartDiscV5(0xc0000001e0)
	/go/src/github.com/status-im/status-go/wakuv2/waku.go:1473 +0x20d
github.com/status-im/status-go/wakuv2.(*Waku).seedBootnodesForDiscV5(0xc0000001e0)
	/go/src/github.com/status-im/status-go/wakuv2/waku.go:1425 +0x2ac
created by github.com/status-im/status-go/wakuv2.(*Waku).Start
	/go/src/github.com/status-im/status-go/wakuv2/waku.go:1211 +0x10a
```

# Notes

The config used:
```json
{
  "LogLevel": "INFO",
  "WakuConfig": {
    "Enabled": false
  },
  "WakuV2Config": {
    "Enabled": true,
  },
  "ClusterConfig": {
    "Enabled": true,
    "DiscV5BootstrapNodes": [
      "enr:-M-4QLOTEs_ZFxCb09FgIezZd5KeTru5CWWyEtMWMN-yUABrerWxckU-pMIh3yO8VjxHpgZ4jU2WSXuK3goW4uYb6c4BgmlkgnY0gmlwhI_G-a6KbXVsdGlhZGRyc7EALzYobm9kZS0wMS5kby1hbXMzLnN0YXR1cy5wcm9kLnN0YXR1c2ltLm5ldAYBu94DiXNlY3AyNTZrMaECoVyonsTGEQvVioM562Q1fjzTb_vKD152PPIdsV7sM6SDdGNwgnZfg3VkcIIjKIV3YWt1MgM"
    ]
  }
}
```
ENR taken from https://fleets.status.im/ for `node-01.do-ams3.status.prod`.

**Comment by richard-ramos** [comment]
Fixed in https://github.com/status-im/status-go/pull/3229

Also since you're setting discv5bootstrapnodes, you need to modify `WakuV2Config` to be like this:
```
 "WakuV2Config": {
    "Enabled": true,
    "EnableDiscV5": true
  },
```

**Comment by jakubgs** [comment]
Probably fixed.
