### ISSUE TITLE
wakuext_peers RPC call causes crash

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#3246]
While testing `statusteam/status-go:v0.135.1-226fa7` on our `notify.prod` fleet to check if newest versions resolve memory leak issues I identified I noticed a problem with the `wakuext_peers` RPC call:
```
admin@node-01.do-ams3.notify.prod:/docker/status-go % /docker/status-go/rpc.sh wakuext_peers
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "method handler crashed"
  }
}
```
I have tested this with Waku v2 enabled and Waku v1 disabled. The log I'm getting when it happens is:
```
ERROR[03-01|19:10:41.488] RPC method wakuext_peers crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 4311 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x1fb22c0, 0x3b2c650})
#011/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/status-im/status-go/protocol.(*Messenger).Peers(...)
#011/go/src/github.com/status-im/status-go/protocol/messenger_peers.go:30
github.com/status-im/status-go/services/ext.(*PublicAPI).Peers(0x1?)
#011/go/src/github.com/status-im/status-go/services/ext/api.go:1221 +0x1a
reflect.Value.call({0xc0010bd920?, 0xc0010c3a20?, 0x7f0c31c2c108?}, {0x22ca980, 0x4}, {0xc004c49410, 0x1, 0xd97e92?})
#011/usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xc0010bd920?, 0xc0010c3a20?, 0x0?}, {0xc004c49410, 0x1, 0x2})
#011/usr/local/go/src/reflect/value.go:339 +0xbf
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc00110fb00, {0x2abe2d0?, 0xc004c9a500}, {0xc003e377c0, 0xd}, {0x3f845b0, 0x0, 0x4d4757?})
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:205 +0x3f0
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc003e377e0?, {0x2abe2d0?, 0xc004c9a500?}, 0xc004c0aa80, 0x0?, {0x3f845b0?, 0x1c0?, 0x0?})
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:391 +0x45
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc00592e990, 0xc004c493b0, 0xc004c0aa80)
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:336 +0x239
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc00592e990, 0xc002d5f400?, 0xc004c0aa80)
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:297 +0x237
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc004c493b0)
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:138 +0x35
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:225 +0xc5
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
#011/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:221 +0x8d
```

**Comment by igor-sirotin** [comment]
The new `push-notification-server` was deployed recently, so I hope there's no issues atm. 
Please reopen if the issue persist.
