### ISSUE TITLE
Panic on `statusd wnode` coomand

### ISSUE THREAD

**Issue by divan** [status-im/status-go#437]
# Problem

On running `statusd wnode` command program halts with panic:

```
$ ./statusd wnode
Starting Whisper/5 node..
Whisper Config: {
    "Enabled": true,
    "IdentityFile": "",
    "PasswordFile": "",
    "EchoMode": true,
    "BootstrapNode": true,
    "ForwarderNode": false,
    "MailServerNode": false,
    "NotificationServerNode": false,
    "DataDir": "statusd-data/wnode",
    "Port": 30379,
    "MinimumPoW": 0.001,
    "TTL": 120,
    "FirebaseConfig": {
        "AuthorizationKeyFile": "",
        "NotificationTriggerURL": "https://fcm.googleapis.com/fcm/send"
    }
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4964956]

goroutine 37 [running]:
github.com/status-im/status-go/geth/rpc.(*Client).RegisterHandler(0x0, 0x4c30ca4, 0xc, 0xc4205c62e0)
	/Users/divan/src/github.com/status-im/status-go/geth/rpc/client.go:103 +0x26
github.com/status-im/status-go/geth/api.(*StatusBackend).registerHandlers(0xc4205c0320, 0x0, 0x0)
	/Users/divan/src/github.com/status-im/status-go/geth/api/backend.go:234 +0x86
github.com/status-im/status-go/geth/api.(*StatusBackend).onNodeStart(0xc4205c0320, 0xc420f4f5c0, 0xc420f4f680)
	/Users/divan/src/github.com/status-im/status-go/geth/api/backend.go:97 +0x46
created by github.com/status-im/status-go/geth/api.(*StatusBackend).StartNode
	/Users/divan/src/github.com/status-im/status-go/geth/api/backend.go:88 +0x14b
```

# Implementation

Panic seems to be related to the RPC initialization and started node state. Need to investigate what exactly we need to start in order for wnode to work properly, first.

# Acceptance Criteria

 - On `statusd wnode` there is no panic message and command launches command line interface ready to use

**Comment by divan** [comment]
Fixed in develop.
