### ISSUE TITLE
TestMessengerContactRequestSuite

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#4697]
```
TestMessengerContactRequestSuite – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAcceptCRRemoveAndRepeat – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAcceptLatestContactRequestForContact – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceOfflineRetractsAndAddsCorrectOrder – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceOfflineRetractsAndAddsWrongOrder – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceRecoverStateReceiveContactRequest – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceRecoverStateSendContactRequest – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceResendsContactRequestAfterRemovingBobFromContacts – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceRestoresOutgoingContactRequestFromSyncInstallationContactV2 – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceSeesOnlyOneAcceptFromBob – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestAliceTriesToSpamBobWithContactRequests – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestBlockedContactSyncing – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestBobRestoresIncomingContactRequestFromSyncInstallationContactV2 – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestBobSendsContactRequestAfterDecliningOneFromAlice – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestBuildContact – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestDismissLatestContactRequestForContact – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestPairedDevicesRemoveContact – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestReceiveAcceptAndRetractContactRequest – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestReceiveAcceptAndRetractContactRequestOutOfOrder – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestReceiveAndAcceptContactRequest – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestReceiveAndAcceptContactRequestTwice – github.com/status-im/status-go/protocol
TestMessengerContactRequestSuite/TestReceiveAndDismissContactRequest – github.com/status-im/status-go/protocol
```

```
panic: send on closed channel

goroutine 934259 [running]:
github.com/status-im/status-go/protocol/common.(*MessageSender).notifyOnSentMessage(0xc012b1ce00, 0xc005cb5200)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/protocol/common/message_sender.go:1190 +0xb3
github.com/status-im/status-go/protocol/common.(*MessageSender).sendMessageSpec(0xc012b1ce00, {0x3289d30, 0xc0000582a8}, 0xc00fa6d040, 0xc005cb4cf0, {0x4c503b8, 0x0, 0x0})
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/protocol/common/message_sender.go:1171 +0x569
github.com/status-im/status-go/protocol/common.(*MessageSender).SendMessageSpec(...)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/protocol/common/message_sender.go:1122
github.com/status-im/status-go/protocol.(*Messenger).sendDataSync(0xc013f6a600, {0x4, 0xff, 0xe, 0x68, 0x27, 0xf2, 0xa2, 0xca, 0x32, ...}, ...)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/protocol/messenger_peersyncing.go:333 +0x765
github.com/status-im/status-go/protocol/datasync.(*NodeTransport).Send(0xc023d9c2b8, {0x4, 0x85, 0x9a, 0xd1, 0xfe, 0x1e, 0xb6, 0x53, 0xc0, ...}, ...)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/protocol/datasync/transport.go:56 +0x83
github.com/status-im/mvds/node.(*Node).sendMessages.func2({0x4, 0xff, 0xe, 0x68, 0x27, 0xf2, 0xa2, 0xca, 0x32, 0xf7, ...}, ...)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/vendor/github.com/status-im/mvds/node/node.go:351 +0xf7
github.com/status-im/mvds/node.(*payloads).MapAndClear(0xc004a23aa0, 0xc012c55ce0)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/vendor/github.com/status-im/mvds/node/payloads.go:75 +0x164
github.com/status-im/mvds/node.(*Node).sendMessages(0xc004a23a40)
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/vendor/github.com/status-im/mvds/node/node.go:350 +0x1f9
github.com/status-im/mvds/node.(*Node).Start.func2()
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/vendor/github.com/status-im/mvds/node/node.go:187 +0x25c
created by github.com/status-im/mvds/node.(*Node).Start
	/home/jenkins/workspace/status-go_prs_tests_PR-4691/vendor/github.com/status-im/mvds/node/node.go:178 +0xab
```

**Comment by MishkaRogachev** [comment]
Resolved by https://github.com/status-im/status-go/pull/4741

Locally test run `go test -run TestMessengerContactRequestSuite -count 10` without issues
