### ISSUE TITLE
Flaky crash in `TestRequestMultipleCommunities `

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#4715]
# Problem

1. `TestRequestMultipleCommunities`
This one crashes for me locally.
```go
github.com/status-im/status-go/protocol/common.(*MessageSender).handleEncryptionLayer
	/Users/igorsirotin/Repositories/Status/status-go/protocol/common/message_sender.go:968
github.com/status-im/status-go/protocol/common.(*MessageSender).handleMessage
	/Users/igorsirotin/Repositories/Status/status-go/protocol/common/message_sender.go:910
github.com/status-im/status-go/protocol/common.(*MessageSender).HandleMessages
	/Users/igorsirotin/Repositories/Status/status-go/protocol/common/message_sender.go:787
github.com/status-im/status-go/protocol.(*Messenger).handleRetrievedMessages
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger.go:3759
github.com/status-im/status-go/protocol.(*Messenger).RetrieveAll
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger.go:3333
github.com/status-im/status-go/protocol.(*Messenger).ProcessAllMessages
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger.go:3354
github.com/status-im/status-go/protocol.(*storeNodeRequest).shouldFetchNextPage
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_store_node_request_manager.go:370
github.com/status-im/status-go/protocol.processMailserverBatch.func2
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:760
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xb0 pc=0x105e11eb8]

goroutine 57300 [running]:
github.com/status-im/status-go/protocol.(*MessengerSignalsHandlerMock).HistoryRequestStarted(0x140091e16e8?, 0x14000c379e0?)
	<autogenerated>:1 +0x28
github.com/status-im/status-go/protocol.(*Messenger).syncFiltersFrom(0x1400e986300, {0x14008529540?, 0x5, 0x8}, 0x0)
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:475 +0x41c
github.com/status-im/status-go/protocol.(*Messenger).syncFilters(...)
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:584
github.com/status-im/status-go/protocol.(*Messenger).RequestAllHistoricMessages(0x1400e986300, 0x0)
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:340 +0x140
github.com/status-im/status-go/protocol.(*Messenger).RequestAllHistoricMessagesWithRetries.func1()
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:308 +0x24
github.com/status-im/status-go/protocol.(*Messenger).performMailserverRequest(0x1400e986300, 0x140091e1ee0)
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:123 +0x1d8
github.com/status-im/status-go/protocol.(*Messenger).RequestAllHistoricMessagesWithRetries(0x14007d85788?, 0xc8?)
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver.go:307 +0x3c
github.com/status-im/status-go/protocol.(*Messenger).asyncRequestAllHistoricMessages.func1()
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver_cycle.go:599 +0x2c
created by github.com/status-im/status-go/protocol.(*Messenger).asyncRequestAllHistoricMessages
	/Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_mailserver_cycle.go:598 +0x84

```
Full log:
[scratch_24.log](https://github.com/status-im/status-go/files/14240240/scratch_24.log)

-----

It seems that some of these issues are a consequence of https://github.com/status-im/status-go/pull/4651.
And with https://github.com/status-im/status-go/pull/4703 it becomes even more frequent.

**Comment by igor-sirotin** [comment]
I separated 2 issues out of original one:
- https://github.com/status-im/status-go/issues/4720
- https://github.com/status-im/status-go/issues/4717

Will rename this one and only keep the crash story.
