### ISSUE TITLE
Prepare steps and examples for wallet API tests

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-go#5175]
# Problem
Prepare configuration and steps to setup status-go as daemon with wallet API exposed via RPC to facilitate testing.

# Acceptance Criteria
- Exact steps to execute to have status-go daemon running with wallet API exposed
- Order of wallet initialisation 
- Examples of wallet JSON-RPC requests

# Steps
// Run statusd with config and seed-phrase for account creation:
`./build/bin/statusd -c ./config.json -log DEBUG --seed-phrase="test test test test test test test test test test test junk"`

// config.json:
// HttpHost and HttpPort are http server address for RPC requests
```
{
    "DataDir": "/tmp/status-go-data",
    "NodeKey": "b5c65bcfdb02261052b71cb5f6dec095d0e10df649b4a2b7d881e55e306cbebc",
    "Rendezvous": false,
    "NoDiscovery": false,
    "ListenAddr": "0.0.0.0:30303",
    "HTTPEnabled": true,
    "HTTPHost": "0.0.0.0",
    "HTTPPort": 3333,
    "APIModules": "eth,admin,wallet",
    "WalletConfig": {
      "Enabled": true
    },
    "WakuConfig": {
        "Enabled": false
    },
    "Networks": [
        {
            "ChainID": 11155111,
            "RPCURL": "http://localhost:8545"
        }
    ]
}
```

// Initializes transfer controller and starts fetching transfer history
```
{
  "jsonrpc": "2.0",
  "id": 37,
  "method": "wallet_checkRecentHistoryForChainIDs",
  "params": [
    [
      11155111,
      11155420,
      421614
    ],
    [
      "0xad05399d2864f4c1ac5e51c73f022021be8c795f",
      "0xb814b99b59f319405691fd131f7db97d34f4c4a7"
    ]
  ]
}
```

// Send ETH transfer
```
{
  "jsonrpc": "2.0",
  "id": 116,
  "method": "wallet_createMultiTransaction",
  "params": [
    {
      "fromAddress": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "fromAmount": "0x5af3107a4000",
      "fromAsset": "ETH",
      "multiTxType": "MultiTransactionSend",
      "toAddress": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
      "toAsset": "ETH"
    },
    [
      {
        "bridgeName": "Transfer",
        "chainID": 11155111,
        "transferTx": {
          "data": "",
          "from": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
          "gas": "0x5BBF",
          "input": "",
          "maxFeePerGas": "0xbcc0f04fd",
          "maxPriorityFeePerGas": "0x3b9aca00",
          "to": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
          "type": "0x02",
          "value": "0x5af3107a4000"
        }
      }
    ],
    "password"
  ]
}'
```

// Until balance contract is deployed to Foundry/Hardhat/Ganache network, transactions, new transfers detection does not work
// To confirm the transaction we could check tx details (params is tx hash)
```
curl -XPOST http://127.0.0.1:3333 -H 'Content-type: application/json' -d '
{
  "jsonrpc": "2.0",
  "id": 45,
  "method": "wallet_getTxDetails",
  "params": [
      "0x1e649f26c6e76ed034f4fed001e601ee86212e571400eb0bff2417ba3c9a5506"
  ]
}
'
```

// If balance contract is deployed, we can check the multitransaction entry exists:
// params: multi transaction id returned by `createMultiTransaction` method
// NOTE: currently error is not returned from this method if no entry. Instead a dummy entry with empty id is returned
```
curl -XPOST http://127.0.0.1:3333 -H 'Content-type: application/json' -d '
{
  "jsonrpc": "2.0",
  "id": 45,
  "method": "wallet_getMultiTxDetails",
  "params": [
      1717255465976
  ]
}
'
```

// We can check pending tx details. This method is deprecated, but since new transfers are not detected, pending tx never disappears
// from pending_transactions DB table, but its status is set to "Success". Then only way to retrieve it is this method:
```
curl -XPOST http://127.0.0.1:3333 -H 'Content-type: application/json' -d '
{
  "jsonrpc": "2.0",
  "id": 45,
  "method": "wallet_getPendingTransactionsForIdentities",
  "params": [
    [
      {
        "chainId": 11155111,
        "hash": "0x1e649f26c6e76ed034f4fed001e601ee86212e571400eb0bff2417ba3c9a5506"
      }
    ]
  ]
}
'
```

// If balance contract is deployed to testing network, balances can be checked with
```
curl -XPOST http://127.0.0.1:3333 -H 'Content-type: application/json' -d '
{
  "jsonrpc": "2.0",
  "id": 195,
  "method": "wallet_fetchOrGetCachedWalletBalances",
  "params": [
    [
      "0xad05399d2864f4c1ac5e51c73f022021be8c795f"
    ]
  ]
}
'
```

# Commands dumped from Desktop app (dups removed)
[wallet_rpc_requests.txt](https://github.com/user-attachments/files/15526630/wallet_rpc_requests_send_transactions_pretty_2.txt)

**Comment by IvanBelyakoff** [comment]
@antdanchenko Please check the issue description and the corresponding PR

**Comment by antdanchenko** [comment]
I've checked out https://github.com/status-im/status-go/pull/5274, ran `make statusgo` and then `./build/bin/statusd -c ./config.json -log DEBUG --seed-phrase="test test test test test test test test test test test junk"` using config.json from the example, 

got an error ` password is required when seed phrase is provided package=status-go/cmd/statusd`

after providing password, got a crash:
```
BUG[06-03|00:02:09.504|github.com/status-im/status-go/services/wallet/collectibles/commands.go:255]       start loadOwnedCollectiblesCommand       chain=31337 account=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
DEBUG[06-03|00:02:09.504|github.com/status-im/status-go/services/wallet/collectibles/commands.go:279]       start loadOwnedCollectiblesCommand       chain=31337 account=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 page=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100dd75b8]

goroutine 905 [running]:
github.com/status-im/status-go/services/wallet/connection.(*Status).GetState(0x3733333133000000?)
	/Users/anton/Status/status-go/services/wallet/connection/status.go:55 +0x28
github.com/status-im/status-go/services/wallet/connection.(*Status).SetIsConnected(0x102872700?, 0x0)
	/Users/anton/Status/status-go/services/wallet/connection/status.go:34 +0x5c
github.com/status-im/status-go/services/wallet/collectibles.(*Manager).checkConnectionStatus(0x14000e12780, 0x14000b40140?)
	/Users/anton/Status/status-go/services/wallet/collectibles/manager.go:910 +0x11c
github.com/status-im/status-go/services/wallet/collectibles.(*Manager).FetchAllAssetsByOwner(0x14000e12780, {0x102c352d8?, 0x14000b8ad20?}, 0x7a69, {0xf3, 0x9f, 0xd6, 0xe5, 0x1a, 0xad, ...}, ...)
	/Users/anton/Status/status-go/services/wallet/collectibles/manager.go:259 +0x56c
github.com/status-im/status-go/services/wallet/collectibles.(*Manager).FetchCollectibleOwnershipByOwner(0x4?, {0x102c352d8, 0x14000b8ad20}, 0x6?, {0xf3, 0x9f, 0xd6, 0xe5, 0x1a, 0xad, ...}, ...)
	/Users/anton/Status/status-go/services/wallet/collectibles/manager.go:360 +0x50
github.com/status-im/status-go/services/wallet/collectibles.(*loadOwnedCollectiblesCommand).Run(0x14000b9e9a0, {0x102c352d8, 0x14000b8ad20})
	/Users/anton/Status/status-go/services/wallet/collectibles/commands.go:281 +0x404
github.com/status-im/status-go/services/wallet/async.(*Group).Add.func1()
	/Users/anton/Status/status-go/services/wallet/async/async.go:107 +0x3c
created by github.com/status-im/status-go/services/wallet/async.(*Group).Add in goroutine 1058
	/Users/anton/Status/status-go/services/wallet/async/async.go:106 +0x84
```

**Comment by IvanBelyakoff** [comment]
The issue @antdanchenko had is resolved by rebasing
