### ISSUE TITLE
Random crashes in node e2e tests

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#539]
# Problem

Node e2e test randomly crashed on this Travis job `https://travis-ci.org/status-im/status-go/jobs/325584660`. It might be not limited to node e2e tests.

```
go test -timeout 5m ./e2e/node/... -network=
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa61da2]
goroutine 529 [running]:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc4212f6e40)
	/home/travis/gopath/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:416 +0x302
created by github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
	/home/travis/gopath/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:112 +0x104
FAIL	github.com/status-im/status-go/e2e/node	18.501s
make: *** [test-e2e] Error 1
```

# Acceptance Criteria

1. Root cause needs to be found
2. Tests made stable
3. Ideally, fix submitted upstream, as it looks like a concurrency issue in go-ethereum

**Comment by dshulyak** [comment]
Another failure https://travis-ci.org/status-im/status-go/jobs/326269561. Now in the API tests 

```
go test -timeout 5m ./e2e/api/... -network=
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc4e502]```

**Comment by divan** [comment]
That looks like a dup of https://github.com/status-im/status-go/issues/429

**Comment by dshulyak** [comment]
thanks, closing this one
