### ISSUE TITLE
Flaky test: `TestPostToCommunityChat`

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#5759]
# Problem

The test itself passes fine, but panics during `TeardownTest`.
Note the `97.861s` runtime, the test runs quickly, then it hangs for 1-2 mintues and eventually panics.

```nim
goroutine 140931 [running]:
github.com/libp2p/go-libp2p-pubsub.(*Subscription).Topic(...)
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/libp2p/go-libp2p-pubsub/subscription.go:21
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).unsubscribeFromPubsubTopic(0x14016636200, 0x1401e379880)
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:506 +0x2c
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).Unsubscribe(0x14016636200, {0x14001083e48?, 0x102f0af14?}, {{0x1401a73ed80?, 0x1401025be00?}, 0x140166efb30?})
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:492 +0x2d4
github.com/status-im/status-go/wakuv2.(*Waku).subscribeToPubsubTopicWithWakuRelay.func1()
        /Users/igorsirotin/Repositories/Status/status-go/wakuv2/waku.go:652 +0x230
created by github.com/status-im/status-go/wakuv2.(*Waku).subscribeToPubsubTopicWithWakuRelay in goroutine 135831
        /Users/igorsirotin/Repositories/Status/status-go/wakuv2/waku.go:647 +0x2a4
FAIL    github.com/status-im/status-go/protocol 97.861s
```

# Race condition

Found by go race detector:

```nim
==================
WARNING: DATA RACE
Read at 0x00c000920e90 by goroutine 5273:
  github.com/waku-org/go-waku/waku/v2/protocol/relay.(*broadcaster).UnRegister()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/broadcast.go:218 +0x3c
  github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).unsubscribeFromPubsubTopic()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:515 +0x244
  github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).Unsubscribe()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:495 +0x730
  github.com/status-im/status-go/wakuv2.(*Waku).subscribeToPubsubTopicWithWakuRelay.func1()
      /Users/igorsirotin/Repositories/Status/status-go/wakuv2/waku.go:657 +0x42c

Previous write at 0x00c000920e90 by goroutine 50:
  github.com/waku-org/go-waku/waku/v2/protocol/relay.(*Subscriptions).close()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/broadcast.go:128 +0x130
  github.com/waku-org/go-waku/waku/v2/protocol/relay.(*broadcaster).Stop()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/broadcast.go:196 +0x64
  github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).Stop()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:506 +0x64
  github.com/status-im/status-go/wakuv2.(*Waku).Stop()
      /Users/igorsirotin/Repositories/Status/status-go/wakuv2/waku.go:1294 +0x124
  github.com/status-im/status-go/protocol.(*MessengerCommunitiesShardingSuite).TearDownTest()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities_sharding_test.go:107 +0x140
  github.com/stretchr/testify/suite.Run.func1.1()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/stretchr/testify/suite/suite.go:184 +0x26c
  runtime.deferreturn()
      /Users/igorsirotin/go/go1.21.8/src/runtime/panic.go:477 +0x34
  testing.tRunner()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1595 +0x1b0
  testing.(*T).Run.func1()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1648 +0x40

Goroutine 5273 (running) created at:
  github.com/status-im/status-go/wakuv2.(*Waku).subscribeToPubsubTopicWithWakuRelay()
      /Users/igorsirotin/Repositories/Status/status-go/wakuv2/waku.go:651 +0x54c
  github.com/status-im/status-go/wakuv2.(*Waku).SubscribeToPubsubTopic()
      /Users/igorsirotin/Repositories/Status/status-go/wakuv2/waku.go:1524 +0xc4
  github.com/status-im/status-go/eth-node/bridge/geth.(*gethWakuV2Wrapper).SubscribeToPubsubTopic()
      /Users/igorsirotin/Repositories/Status/status-go/eth-node/bridge/geth/wakuv2.go:238 +0x50
  github.com/status-im/status-go/protocol/transport.(*Transport).SubscribeToPubsubTopic()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/transport/transport.go:703 +0x80
  github.com/status-im/status-go/protocol.(*Messenger).subscribeToCommunityShard()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities.go:1062 +0xe8
  github.com/status-im/status-go/protocol.(*Messenger).UpdateCommunityFilters()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities.go:2720 +0x534
  github.com/status-im/status-go/protocol.(*Messenger).SetCommunityShard()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities.go:2615 +0x584
  github.com/status-im/status-go/protocol.(*MessengerCommunitiesShardingSuite).testPostToCommunityChat()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities_sharding_test.go:124 +0x344
  github.com/status-im/status-go/protocol.(*MessengerCommunitiesShardingSuite).TestPostToCommunityChat.func1()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities_sharding_test.go:197 +0x60
  github.com/stretchr/testify/suite.(*Suite).Run.func1()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/stretchr/testify/suite/suite.go:115 +0x1b8
  testing.tRunner()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1595 +0x1b0
  testing.(*T).Run.func1()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1648 +0x40

Goroutine 50 (running) created at:
  testing.(*T).Run()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1648 +0x5e8
  github.com/stretchr/testify/suite.runTests()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/stretchr/testify/suite/suite.go:247 +0x170
  github.com/stretchr/testify/suite.Run()
      /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/stretchr/testify/suite/suite.go:220 +0x79c
  github.com/status-im/status-go/protocol.TestMessengerCommunitiesShardingSuite()
      /Users/igorsirotin/Repositories/Status/status-go/protocol/messenger_communities_sharding_test.go:23 +0x40
  testing.tRunner()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1595 +0x1b0
  testing.(*T).Run.func1()
      /Users/igorsirotin/go/go1.21.8/src/testing/testing.go:1648 +0x40
==================

```

# Notes

Tried to fix it with this, didn't help:
- https://github.com/waku-org/go-waku/pull/1201

**Comment by igor-sirotin** [comment]
I think I found the issue.

The crash happens here with `topicData.subscription == nil`:
https://github.com/status-im/status-go/blob/bb6205791e2322798430d02b6756dec5b3d3993d/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go#L521

We create new `topicData` here in `upsertTopic`:
https://github.com/status-im/status-go/blob/bb6205791e2322798430d02b6756dec5b3d3993d/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go#L206-L208

It's created with `subscription == nil`

We call `upsertTopic` in 2 places:

1.  Inside `subscribeToPubsubTopic`
    https://github.com/status-im/status-go/blob/bb6205791e2322798430d02b6756dec5b3d3993d/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go#L229
    ✅ We do create set subscription here:
    https://github.com/status-im/status-go/blob/bb6205791e2322798430d02b6756dec5b3d3993d/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go#L250-L252

2. Inside `Publish`:
    https://github.com/status-im/status-go/blob/bb6205791e2322798430d02b6756dec5b3d3993d/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go#L306-L309
    ❌ In this case we don't set the subscription. And get the panic when unsubscribing.

**Comment by richard-ramos** [comment]
@igor-sirotin, I think your analysis is correct.
But, besides this bug, does this mean we're Publishing to a topic without being subscribed to it?

**Comment by igor-sirotin** [comment]
> But, besides this bug, does this mean we're Publishing to a topic without being subscribed to it?

@richard-ramos well, looks like so, yes :)
Is that forbidden or just doesn't make sense?

I'll take a look how that happens

**Comment by richard-ramos** [comment]
Hm i think you need to be subscribed otherwise there might not be any peers to broadcast the message, so it's likely that we'll need to add something like this to the publish function:
```
		//Check if gossipsub subscription already exists for pubSubTopic
		if !w.IsSubscribed(pubSubTopic) {
			_, err := w.subscribeToPubsubTopic(cFilter.PubsubTopic)
			if err != nil {
				//TODO: Handle partial errors.
				w.log.Error("failed to subscribe to pubsubTopic", zap.Error(err), zap.String("pubsubTopic", cFilter.PubsubTopic))
				return nil, err
			}
		}
```

**Comment by igor-sirotin** [comment]
# 1. Some related weirdness found

Here's how the first change of community shard looks like this: (with some logs added)

```nim
2024-08-22T17:35:11.530+0100    INFO    waku-owner.node2.relay  relay/waku_relay.go:422 subscribing to  {"pubsubTopic": "/waku/2/rs/16/128", "contentTopics": []}
2024-08-22T17:35:11.530+0100    INFO    waku-owner.node2.relay  relay/waku_relay.go:223 subscribing to underlying pubsubTopic   {"pubsubTopic": "/waku/2/rs/16/128"}
<<< WakuRelay.Publish before upsertTopic. topic: /waku/2/rs/16/128
<<< upsertTopic. topic: /waku/2/rs/16/128, found: false, topicaData: <nil>
<<< upsertTopic. added new. topic: /waku/2/rs/16/128, found: false, topicData: &{0x140030ac420 <nil> <nil> map[]}
<<< WakuRelay.Publish after upsertTopic. pubSubTopic: /waku/2/rs/16/128
2024-08-22T17:35:11.530+0100    WARN    pubsub  go-libp2p-pubsub/tag_tracer.go:122      unable to create decaying delivery tag: decaying tag with name pubsub-deliveries:/waku/2/rs/16/128 already exists
2024-08-22T17:35:11.530+0100    INFO    waku-owner.node2.relay  relay/waku_relay.go:259 gossipsub subscription  {"pubsubTopic": "/waku/2/rs/16/128"}
2024-08-22T17:35:11.530+0100    INFO    waku-owner      publish/message_sender.go:130   publishing message via relay    {"envelopeHash": "0x3ece0c7c5fd76b0acfc3eb5aa71ef7863193711ae42a3743550eaaa8d296f3f4", "pubsubTopic": "/waku/2/rs/16/128", "contentTopic": "/waku/1/0xd99100cf/rfc26", "timestamp": 1724344511530773000, "peerCnt": 0}
2024-08-22T17:35:11.530+0100    INFO    waku-owner.node2.peer-manager   peermanager/topic_event_handler.go:26   handleNewRelayTopicSubscription {"pubSubTopic": "/waku/2/rs/16/128"}
2024-08-22T17:35:11.530+0100    ERROR   waku-owner      wakuv2/message_publishing.go:100        could not send message  {"envelopeHash": "0x3ece0c7c5fd76b0acfc3eb5aa71ef7863193711ae42a3743550eaaa8d296f3f4", "pubsubTopic": "/waku/2/rs/16/128", "contentTopic": "/waku/1/0xd99100cf/rfc26", "timestamp": 1724344511530773000, "error": "not enough peers to publish"}
```

Note the order:
- subscribing to underlying 
- WakuRelay.Publish
- gossipsub subscription  {"pubsubTopic": "/waku/2/rs/16/128"}
- could not send message: not enough peers to publish

It happens in 2 goroutines.
And it's not just once, it happens every time subscribing to some pubsubtopic in this case.

Not sure what conclusion to make, but this doesn't sound right.
Also, not sure how would subscribing during `Publish` would work in this case then.

# 2. Why is `Publish` is  called after `Unsubscribe`

https://github.com/status-im/status-go/blob/bb6205791e2322798430d02b6756dec5b3d3993d/protocol/messenger_communities_sharding_test.go#L172-L185

1. We set the community shard to 128
2. Test that alice receives shard info
3. Test that alice receives messages from owner on shard 128
4. Change community shard to 256
At this point we unsubscribe from shard 128. 
And then send the new shard info. But we should send it on previous shard, so we do it on shard 128.
⚠️ And this is how we call `Publish` without being subscribed. And it seem to be working fine, 1 peer found.
        
    <details>
        <summary>Log</summary>
    
    ```nim
    <<< WakuRelay.Unsubscribe - start. pubsubTopic: /waku/2/rs/16/128, contentTopics: map[]
    <<< WakuRelay.Unsubscribe - mutex acquired. pubsubTopic: /waku/2/rs/16/128
    <<< WakuRelay.Unsubscribe - loop over map. contentFilter.pubsubTopic: /waku/2/rs/16/128, pubsubTopic: /waku/2/rs/16/128, topicData: &{0x140030ac420 0x14019da1e50 0x14017cfb920 map[4:0x14002894dc0]}
    <<< WakuRelay.Unsubscribe - pubsubUnsubscribe. contentFilter.pubsubTopic: /waku/2/rs/16/128, pubsubTopic: /waku/2/rs/16/128, topicData: &{0x140030ac420 0x14019da1e50 0x14017cfb920 map[]}
    <<< unsubscribeFromPubsubTopic. topicData: &{0x140030ac420 0x14019da1e50 0x14017cfb920 map[]}, topic: /waku/2/rs/16/128
    2024-08-22T17:35:12.051+0100    INFO    waku-owner.node2.relay  relay/waku_relay.go:522 unsubscribing from pubsubTopic  {"topic": "/waku/2/rs/16/128"}
    2024-08-22T17:35:12.052+0100    INFO    waku-owner      publish/message_sender.go:130   publishing message via relay    {"envelopeHash": "0x114127668be35fa12d94bd2a54bec09525e1f54f0ac44b4b146b0b7b922766d4", "pubsubTopic": "/waku/2/rs/16/128", "contentTopic": "/waku/1/0xd99100cf/rfc26", "timestamp": 1724344512046679000, "peerCnt": 1}
    2024-08-22T17:35:12.052+0100    ERROR   waku-owner.node2.relay  relay/waku_relay.go:555 getting message from subscription       {"error": "subscription cancelled"}
    2024-08-22T17:35:12.052+0100    INFO    waku-owner.node2.peer-manager   peermanager/topic_event_handler.go:89   handleNewRelayTopicUnSubscription       {"pubSubTopic": "/waku/2/rs/16/128"}
    <<< WakuRelay.Publish before upsertTopic. pubsubTopic: /waku/2/rs/16/128
    <<< upsertTopic. topic: /waku/2/rs/16/128, found: false, topicaData: <nil>
    <<< upsertTopic. added new. topic: /waku/2/rs/16/128, found: false, topicData: &{0x140193e83c0 <nil> <nil> map[]}
    <<< WakuRelay.Publish after upsertTopic. pubsubTopic: /waku/2/rs/16/128
    ```
    </details>

# 3. The fix

Sounds like the main fix for me is to actually check if `topicData.subscription == nil` in `unsubscribeFromPubsubTopic` 😄 
Yet would be cool to figure out how bad this behaviour is, in general.

https://github.com/status-im/status-go/blob/f91329323c8396841b076efd30511009b546cb78/vendor/github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go#L521-L524

cc @richard-ramos

**Comment by igor-sirotin** [comment]
Hmmm, should we actually force the unsubscription from a shard  when setting a new shard?
https://github.com/status-im/status-go/blob/a00bf6977b1f0b279e20546df575397c36461339/protocol/messenger_communities.go#L2582-L2588

I mean, same shard could be used for a another community, right?
Should unsubscribe be a bit smarter and check it at least?

**Comment by igor-sirotin** [comment]
> i think you need to be subscribed otherwise there might not be any peers to broadcast the message, so it's likely that we'll need to add something like this to the publish function

Though we might indeed fail to publish a message, when should we unsubscribe in such case?
Sounds like it will stay subscribed forever.

**Comment by igor-sirotin** [comment]
Got a new panic now 😵

```nim
<<< WakuRelay.Publish before upsertTopic. topic: /waku/2/rs/16/64
<<< upsertTopic. topic: /waku/2/rs/16/64, found: false, topicaData: <nil>
<<< upsertTopic. added new. topic: /waku/2/rs/16/64, found: false, topicData: &{0x1400b490d20 <nil> <nil> map[]}
<<< WakuRelay.Publish after upsertTopic. pubSubTopic: /waku/2/rs/16/64
2024-08-22T23:17:12.526+0100    WARN    pubsub  go-libp2p-pubsub/tag_tracer.go:122      unable to create decaying delivery tag: decaying tag with name pubsub-deliveries:/waku/2/rs/16/64 already exists
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10161e9ac]

goroutine 110762 [running]:
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).checkAndUpdateTopicHealth(0x1400279b8c0, 0x0)
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:130 +0x2c
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).handlerPeerTopicEvent(0x1400279b8c0, {{0x1400e2fe320, 0x10}, {0x14002754420, 0x27}, 0x0})
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/topic_event_handler.go:148 +0x574
github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).peerEventLoop(0x1400279b8c0, {0x104e1bb28, 0x140042b9c20})
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/topic_event_handler.go:173 +0x1e0
created by github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).Start in goroutine 109084
        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:243 +0xf8
FAIL    github.com/status-im/status-go/protocol 77.783s
FAIL
```

**Comment by richard-ramos** [comment]
> I mean, same shard could be used for a another community, right?
Should unsubscribe be a bit smarter and check it at least?

In the case of communities as they're currently coded, each community shard is DoS protected, and as such it should have its own private key and not share shards with other communities, so I think it should be fine to unsubscribe from the shard *for now*

> Though we might indeed fail to publish a message, when should we unsubscribe in such case?
Sounds like it will stay subscribed forever.

Ideally we should unsubscribe when we're no longer interested in receiving messages or publishing to the topic.
So in this flow you describe:
```
- Change community shard to 256
- At this point we unsubscribe from shard 128.
- And then send the new shard info. But we should send it on previous shard, so we do it on shard 128.
⚠️ And this is how we call Publish without being subscribed. And it seem to be working fine, 1 peer found.
```
We need to switch the order of unsubscribing and sending the previous shard info. 
I do also see this flow prone to errors because it's possible that publishing the new shard might fail. So perhaps the way to go is:  Publish the new shard info. Confirm that the message is received by a storenode (this is done with the message verification logic that @kaichaosun implemented, and only then, unsubscribe from the shard.  (Maybe this verification and unsubscribe attempt could be done async?)
