### ISSUE TITLE
Flaky test: `TestService_IncrementalUpdateMixed`

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#6141]
Reproduce easily with `-test.count=100`:
```
=== Failed
=== FAIL: services/wallet/activity  (0.00s)
panic: test timed out after 5m0s
running tests:
	TestService_IncrementalUpdateMixed (4m59s)
```

Test goroutine:
```
goroutine 9738 [select, 4 minutes]:
reflect.rselect({0xc000c177c8, 0x2, 0xc0009c15b8?})
	/nix/store/mf08k94zrnzb2q8x303g14l2ryi2ws3w-go-1.21.10/share/go/src/runtime/select.go:589 +0x2c5
reflect.Select({0xc0002fe630?, 0x2, 0xc0008fc5e8?})
	/nix/store/mf08k94zrnzb2q8x303g14l2ryi2ws3w-go-1.21.10/share/go/src/reflect/value.go:3104 +0x5ea
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc000394150, {0x16b7720?, 0xc0002df3b0?})
	/home/jenkins/workspace/status-go_prs_tests_PR-6111/vendor/github.com/ethereum/go-ethereum/event/feed.go:170 +0x3cc
github.com/status-im/status-go/transactions.(*PendingTxTracker).notifyPendingTransactionListeners(0xc000b085a0, {{0x309, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}}, ...}, ...)
	/home/jenkins/workspace/status-go_prs_tests_PR-6111/transactions/pendingtxtracker.go:750 +0x232
github.com/status-im/status-go/transactions.(*PendingTxTracker).addPendingAndNotify(0xc000b085a0, 0xc000468420)
	/home/jenkins/workspace/status-go_prs_tests_PR-6111/transactions/pendingtxtracker.go:721 +0x16e
github.com/status-im/status-go/transactions.(*PendingTxTracker).StoreAndTrackPendingTx(0xc000b085a0, 0xc000a7b520?)
	/home/jenkins/workspace/status-go_prs_tests_PR-6111/transactions/pendingtxtracker.go:610 +0x57
github.com/status-im/status-go/services/wallet/activity.TestService_IncrementalUpdateMixed(0xc000a7b520)
	/home/jenkins/workspace/status-go_prs_tests_PR-6111/services/wallet/activity/session_service_test.go:106 +0x378
testing.tRunner(0xc000a7b520, 0x1b93e38)
	/nix/store/mf08k94zrnzb2q8x303g14l2ryi2ws3w-go-1.21.10/share/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/nix/store/mf08k94zrnzb2q8x303g14l2ryi2ws3w-go-1.21.10/share/go/src/testing/testing.go:1648 +0x3ad
```

**Comment by igor-sirotin** [comment]
@dlipicar this one is especially painful, because if a test paniced, it's not given any reruns 🙁

**Comment by dlipicar** [comment]
@igor-sirotin I'm on it!
