### ISSUE TITLE
RPC method wakuext_startMessenger crashed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-go#6197]
To reproduce run [test_one_to_one_message_baseline](https://github.com/status-im/status-go/blob/develop/tests-functional/tests/test_one_to_one_messages.py#L21C9-L21C41) 3-5 times

Log:

```
ERROR[12-11|15:42:01.127] RPC method wakuext_startMessenger crashed: runtime error: invalid memory address or nil pointer dereference
2024-12-11 17:42:01 goroutine 1577 [running]:
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:199 +0x85
2024-12-11 17:42:01 panic({0x26fb7e0?, 0x4951220?})
2024-12-11 17:42:01     /usr/local/go/src/runtime/panic.go:914 +0x21f
2024-12-11 17:42:01 github.com/status-im/status-go/protocol.(*Messenger).Start(0x4b6015?)
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/protocol/messenger.go:726 +0x44
2024-12-11 17:42:01 github.com/status-im/status-go/services/ext.(*Service).StartMessenger(0xc001229800)
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/services/ext/service.go:201 +0x7c
2024-12-11 17:42:01 github.com/status-im/status-go/services/ext.(*PublicAPI).StartMessenger(...)
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/services/ext/api.go:799
2024-12-11 17:42:01 reflect.Value.call({0xc001dcf680?, 0xc000e331e0?, 0x7f0a10213090?}, {0x2acd56e, 0x4}, {0xc0013346f0, 0x1, 0x0?})
2024-12-11 17:42:01     /usr/local/go/src/reflect/value.go:596 +0xce7
2024-12-11 17:42:01 reflect.Value.Call({0xc001dcf680?, 0xc000e331e0?, 0x542aa5?}, {0xc0013346f0?, 0x0?, 0xc00136ccb8?})
2024-12-11 17:42:01     /usr/local/go/src/reflect/value.go:380 +0xb9
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc000e75980, {0x3351188?, 0xc0000b5540}, {0xc00132e018, 0x16}, {0x4c508c0, 0x0, 0x4d8a6f?})
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:205 +0x379
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0016f4340?, {0x3351188?, 0xc0000b5540?}, 0xc000868230, 0x0?, {0x4c508c0?, 0x28894a0?, 0xc002645e08?})
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:391 +0x3c
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc00120a7e0, 0xc001334690, 0xc000868230)
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:336 +0x22f
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc00120a7e0, 0x30?, 0xc000868230)
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:297 +0x22d
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc001334690)
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:138 +0x2f
2024-12-11 17:42:01 github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:225 +0xbe
2024-12-11 17:42:01 created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc in goroutine 1269
2024-12-11 17:42:01     /go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:221 +0x79
2024-12-11 17:42:01  
2024-12-11 17:42:01 WARN [12-11|15:42:01.128] Served wakuext_startMessenger            reqid=1 duration=11.359156ms err="method handler crashed"
```

**Comment by igor-sirotin** [comment]
Thanks, I will take a look.
And this makes me think that we should have Sentry set up for tests

**Comment by igor-sirotin** [comment]
Couldn't reproduce
```py
>  pytest -k test_one_to_one_message_baseline --count 10
=========================================================================================================================================================================== test session starts ===========================================================================================================================================================================
platform darwin -- Python 3.13.0, pytest-7.4.0, pluggy-1.6.0 -- /Users/sirotin/Repositories/status/status-go/tests-functional/.venv/bin/python
cachedir: .pytest_cache
docker image: 
waku fleets config file: /usr/status-user/wakufleetconfig.json
waku fleet: status-go.test
push fleets config file: /static/configs/pushfleetconfig.json
disable override networks: False
rootdir: /Users/sirotin/Repositories/status/status-go/tests-functional
configfile: pytest.ini
plugins: repeat-0.9.4, rerunfailures-13.0, Faker-37.6.0, dependency-0.6.0, xdist-3.6.1
collected 3670 items / 3660 deselected / 10 selected                                                                                                                                                                                                                                                                                                                      

tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[1-10] PASSED                                                                                                                                                                                                                                                  [ 10%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[2-10] PASSED                                                                                                                                                                                                                                                  [ 20%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[3-10] PASSED                                                                                                                                                                                                                                                  [ 30%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[4-10] PASSED                                                                                                                                                                                                                                                  [ 40%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[5-10] PASSED                                                                                                                                                                                                                                                  [ 50%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[6-10] PASSED                                                                                                                                                                                                                                                  [ 60%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[7-10] PASSED                                                                                                                                                                                                                                                  [ 70%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[8-10] PASSED                                                                                                                                                                                                                                                  [ 80%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[9-10] PASSED                                                                                                                                                                                                                                                  [ 90%]
tests/reliability/test_one_to_one_messages.py::TestOneToOneMessages::test_one_to_one_message_baseline[10-10] PASSED                                                                                                                                                                                                                                                 [100%]
```

Anyway, the RPC and Messenger code has change significantly since then. Perhaps this got auto-fixied.
